name: build
on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ main ]
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]
    env:
      OS: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          if [ -f test_requirements.txt ]; then pip install -r test_requirements.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
      - name: Unit test with coverage
        run: |
          pytest --exitfirst --verbose --failed-first --cov opnsense_cli --cov-config .coveragerc opnsense_cli
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
      - name: smoke test
        run: |
          pip install .
          mkdir -p /home/runner/.opn-cli
          touch /home/runner/.opn-cli/conf.yaml
          opn-cli version
          opn-cli new command core firewall category --tag categories -m https://raw.githubusercontent.com/opnsense/core/master/src/opnsense/mvc/app/models/OPNsense/Firewall/Category.xml -f https://raw.githubusercontent.com/opnsense/core/master/src/opnsense/mvc/app/controllers/OPNsense/Firewall/forms/categoryEdit.xml
