name: publish docker image
on:
  #workflow_dispatch:
  push:
    branches:
      - 'docker_build'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
    -
      name: Set docker metadata
      #id: step_one
      run: |
        echo "docker_image_name=$(python setup.py --name)" >> $GITHUB_ENV
        echo "docker_tag_version=$(python setup.py --version)" >> $GITHUB_ENV
    -
      name: show docker metadata
      #id: step_two
      run: |
        echo "${{ env.docker_image_name }}"
        echo "${{ env.docker_tag_version }}"

